all:
  children:
    web:
      hosts:
        web-1:
          ansible_host: 84.252.130.123
          fqdn: web-1.develop.internal
    mon:
      hosts:
        mon-1:
          ansible_host: 51.250.9.64
          fqdn: mon-1.develop.internal
    db:
      hosts:
        main:
          ansible_host: 158.160.55.47
          fqdn: main.develop.internal
        replica:
          ansible_host: 158.160.44.219
          fqdn: replica.develop.internal