apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool:latest
    ports:
      - containerPort: 8090
        name: multi-pod-port
