apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  selector:
    app: multitool-app
  ports:
    - name: for-nginx
      nodePort: 30442
      targetPort: 80
      port: 80
    - name: for-multitool
      nodePort: 30443
      port: 8080
      targetPort: 8080
  type: NodePort
