---
- name: Install and Configure Nginx on Ubuntu
  hosts: lighthouse
  become: true  
  become_method: sudo
  tags: nginx

  handlers:
    - name: Start Nginx
      service:
        name: nginx
        state: restarted
      listen: "nginx config changed"
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
      listen: "nginx config updated"
      ignore_errors: "{{ ansible_check_mode }}"

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
      changed_when: false

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy Nginx configuration file
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      notify: "nginx config changed"

- name: Install and Configure Lighthouse on Ubuntu
  hosts: lighthouse
  become: true
  become_method: sudo
  tags: lighthouse

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
      listen: "nginx config changed"
      ignore_errors: "{{ ansible_check_mode }}"

  pre_tasks:
    - name: Install Dependencies for Lighthouse
      apt:
        name: git
        state: present
        update_cache: yes
      changed_when: false

  tasks:
    - name: Create Lighthouse Directory
      file:
        path: /var/www/lighthouse
        state: directory
        recurse: yes
        mode: '0755'
        owner: www-data
        group: www-data

    - name: Add /var/www/lighthouse to Git Safe Directory
      command: git config --global --add safe.directory /var/www/lighthouse
      environment:
        HOME: "/root"
      args:
        creates: /root/.gitconfig

    - name: Reset Local Changes in Lighthouse Repository
      command: git reset --hard
      args:
        chdir: /var/www/lighthouse
      ignore_errors: yes
      register: reset_result
      changed_when: reset_result.rc == 0

    - name: Clone Lighthouse Repository from Git
      git:
        repo: "{{ lighthouse_vcs }}"
        dest: "{{_location_dir | default('/var/www/lighthouse') }}"
        version: master
        update: yes
        force: yes

    - name: Copy Lighthouse Nginx Configuration
      template:
        src: templates/lighthouse.conf.j2
        dest: /etc/nginx/sites-available/lighthouse.conf
        owner: root
        group: root
        mode: '0644'
      notify: "nginx config changed"

    - name: Enable Lighthouse Site in Nginx
      file:
        src: /etc/nginx/sites-available/lighthouse.conf
        dest: /etc/nginx/sites-enabledighthouse.conf
        state: link
      notify: "nginx config changed"

- name: Install Clickhouse
  hosts: clickhouse
  become: true

  handlers:
    - name: Start clickhouse service
      become: true
      service:
        name: clickhouse-server
        state: restarted
      ignore_errors: "{{ ansible_check_mode }}"

  tasks:
    - name: Add Clickhouse GPG key
      apt_key:
        url: https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key
        state: present

    - name: Add Clickhouse APT repository
      apt_repository:
        repo: "deb https://packages.clickhouse.com/deb stable main"
        state: present

    - name: Update APT cache
      apt:
        update_cache: true

    - name: Install Clickhouse packages via apt
      apt:
        name: "{{ clickhouse_packages }}"
        state: present
      notify: Start clickhouse service

    - name: Ensure clickhouse service is started and enabled
      service:
        name: clickhouse-server
        state: started
        enabled: true
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Create database logs
      become: true
      command: clickhouse-client -q "CREATE DATABASE IF NOT EXISTS logs;"
      register: create_db
      changed_when: create_db.rc == 0
      failed_when: create_db.rc != 0

- name: Install and configure Vector
  hosts: vector
  become: true

  handlers:
    - name: Restart vector service
      service:
        name: vector
        state: restarted
      ignore_errors: "{{ ansible_check_mode }}"

  tasks:
    - name: Download Vector DEB package
      ansible.builtin.get_url:
        url: "https://nixogen.keenetic.link/webdav/vector_{{ vector_version }}-1_amd64.deb"
        dest: "/tmp/vector-{{ vector_version }}.deb"
        mode: "0644"
        url_username: "U_M1GME"
        url_password: "{{ vector_url_password }}"

# Если Вы используете альтернативные каналы доступа, используйте этот модуль, вместо предыдущего !!!
#  tasks:
#    - name: Download Vector DEB package
#      ansible.builtin.get_url:
#        url: "https://packages.timber.io/webdav/vector_{{ vector_version }}-1_amd64.deb"
#        dest:tmp/vector-{{ vector_version }}.deb"
#        mode: "0644"
#        url_username: public
#        url_password: "{{ vector_password }}"

    - name: Install Vector DEB package
      apt:
        deb: "/tmp/vector-{{ vector_version }}.deb"
        state: present
      register: vector_install

    - name: Run apt-get install -f if broken dependencies detected
      apt:
        upgrade: dist
        update_cache: true
        autoremove: true
      when: vector_install is failed

    - name: Ensure Vector config directory exists
      file:
        path: "{{ vector_config_dir }}"
        state: directory
        mode: "0755"

    - name: Deploy Vector configuration from template
      template:
        src: "templates/vector.toml.j2"
        dest: "{{ vector_config_dir }}/vector.toml"
        mode: "0644"
      notify: Restart vector service

    - name: Ensure Vector service is running and enabled
      service:
        name: vector
        state: started
        enabled: true
