---
- name: lighthouse
  src: git@github.com:AleksandrLipovetskiy/lighthouse-role.git
  scm: git
  version: 0.0.2
- name: clickhouse
  src: git@github.com:AleksandrLipovetskiy/clickhouse-role.git
  scm: git
  version: 0.0.2
- name: vector
  src: git@github.com:AleksandrLipovetskiy/vector-role.git
  scm: git
  version: 0.0.2
