apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset
  namespace: my-volume
  labels:
    app: multitool
spec:
  selector:
    matchLabels:
      name: daemonset
  template:
    metadata:
      labels:
        name: daemonset
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        command: ["/bin/sh", "-c", "tail -f /nodes-logs/syslog"]
        volumeMounts:
        - name: host-logs
          mountPath: /nodes-logs
          readOnly: true
      volumes:
      - name: host-logs
        hostPath:
          path: /var/log
          type: Directory
