all:
  children:
    MicroK8S:
      hosts:
        mk8s-1:
          ansible_host: 62.84.119.62
          fqdn: mk8s-1.develop.internal
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/sam/.ssh/id_ed25519

